# Generated by Django 4.2 on 2023-04-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book_id',
        ),
    ]
