# Generated by Django 4.2 on 2023-05-07 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authors', '0003_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='highlighted',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
        ),
    ]
