# Generated by Django 4.2 on 2023-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(default='none', max_length=100)),
                ('pages', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
