# Generated by Django 4.2 on 2023-04-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_author_id_book_author_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_name',
            new_name='author_id',
        ),
    ]
