# Generated by Django 4.2 on 2023-05-10 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_highlighted_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
    ]
